const fs = require('fs');
const ok = (label, v) => console.log((v ? '[OK]' : '[KO]'), label);
const idx  = fs.readFileSync('index.html', 'utf8');
const sw   = fs.readFileSync('sw.js', 'utf8');
const scr  = fs.readFileSync('script.js', 'utf8');
const cfg  = fs.readFileSync('modules/core/config.js', 'utf8');
const aq   = fs.readFileSync('modules/features/acquisti.js', 'utf8');
const hi   = fs.readFileSync('head-init.js', 'utf8');
const gas  = fs.readFileSync('../gas-backend/Codice.js', 'utf8');
const prod = fs.readFileSync('modules/features/produzione.js', 'utf8');
const man  = JSON.parse(fs.readFileSync('manifest.json', 'utf8'));

ok('F5.1 head-init.js esiste',                    fs.existsSync('head-init.js'));
ok('F5.1 login fn NON inline in index',           !idx.includes('function verificaAccesso'));
ok('F5.1 head-init.js caricato in index',          idx.includes('head-init.js'));
ok('F5.1 CSP base-uri self',                       idx.includes("base-uri 'self'"));
ok('F5.1 CSP form-action self',                    idx.includes("form-action 'self'"));
ok('F5.2 PIN via POST in head-init',               hi.includes("method: 'POST'"));
ok('F5.2 PIN NON in querystring head-init',       !hi.includes('?azione=verificaPinAdmin'));
ok('F5.2 GAS doPost gestisce verificaPinAdmin',    gas.includes("azione === 'verificaPinAdmin'"));
ok('F5.3 _esc() sulle options in acquisti',        aq.includes('_esc(s)'));
ok('F6.1 Font Awesome preload non-blocking',       idx.includes('data-fa-nonblock'));
ok('F6.2 avatar requestIdleCallback',              scr.includes('requestIdleCallback'));
ok('F6.3 SHELL_CACHE_KEY rimosso da config',      !cfg.includes('SHELL_CACHE_KEY'));
ok('F7.2 manifest 4 icone (any+maskable x2)',      man.icons.length === 4);
ok('F7.2 manifest theme_color chiaro',             man.theme_color === '#f8fafc');
ok('F7.3 offline.html esiste',                     fs.existsSync('offline.html'));
ok('F7.3 offline.html in SHELL_ASSETS',            sw.includes('offline.html'));
ok('F7.3 fallback navigazione offline in SW',      sw.includes('isNavigate'));
ok('F7.3 SW prod-shell-v217',                      sw.includes('prod-shell-v217'));
ok('F8.1 modules/core/state.js esiste',            fs.existsSync('modules/core/state.js'));
ok('F8.2 modules/core/repository.js esiste',       fs.existsSync('modules/core/repository.js'));
ok('F8.3 _initModuliENaviga_ estratta in script',  scr.includes('_initModuliENaviga_'));
ok('F8.3 registerUIGlobals 1 sola occorrenza',    (scr.match(/registerUIGlobals/g) || []).length === 1);
ok('F8.3 RevisionPoller.start 1 sola occorrenza', (scr.match(/RevisionPoller\.start/g) || []).length === 1);
ok('F8.2 produzione.js importa da state.js',       prod.includes("from '../core/state.js'"));

const ver = (idx.match(/\?v=(\d{8}[a-z])/) || [])[1];
const swv = (sw.match(/prod-shell-(v\d+)/) || [])[1];
console.log('\nAPP:', ver, '/ SW:', swv, '/ GAS: v157');
